package midpuri.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "QueryMIDPService", targetNamespace = "http://midpuri.org", wsdlLocation = "file:/C:/Projects/QueryMIDPRestService_wsdls/IBCLESS.WSDL")
public class QueryMIDPService
        extends Service {

    private final static URL QUERYMIDPSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYMIDPSERVICE_EXCEPTION;
    private final static QName QUERYMIDPSERVICE_QNAME = new QName("http://midpuri.org", "QueryMIDPService");

    static {
        QUERYMIDPSERVICE_WSDL_LOCATION = midpuri.soap.QueryMIDPService.class.getResource("/wsdls/IBCLESS.WSDL");
        WebServiceException e = null;
        if (QUERYMIDPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("can't find IBCLESS.WSDL.Place the wsdl correctly in classpath");
        }
        QUERYMIDPSERVICE_EXCEPTION = e;
    }

    public QueryMIDPService() {
        super(__getWsdlLocation(), QUERYMIDPSERVICE_QNAME);
    }

    public QueryMIDPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYMIDPSERVICE_QNAME, features);
    }

    public QueryMIDPService(URL wsdlLocation) {
        super(wsdlLocation, QUERYMIDPSERVICE_QNAME);
    }

    public QueryMIDPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYMIDPSERVICE_QNAME, features);
    }

    public QueryMIDPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryMIDPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYMIDPSERVICE_EXCEPTION != null) {
            throw QUERYMIDPSERVICE_EXCEPTION;
        }
        return QUERYMIDPSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns QueryMIDP
     */
    @WebEndpoint(name = "QueryMIDPSoap12")
    public QueryMIDP getQueryMIDPSoap12() {
        return super.getPort(new QName("http://midpuri.org", "QueryMIDPSoap12"), QueryMIDP.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns QueryMIDP
     */
    @WebEndpoint(name = "QueryMIDPSoap12")
    public QueryMIDP getQueryMIDPSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://midpuri.org", "QueryMIDPSoap12"), QueryMIDP.class, features);
    }

}
